[build]
  functions = "netlify/functions" # Tells Netlify where your function source code is

# This rewrite rule is crucial. It takes ALL incoming requests ("/*")
# and sends them to your 'api' function. The :splat captures the rest of the path.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 # HTTP 200 makes it a rewrite (proxy), not a browser redirect