[build]
  functions = "netlify/functions"

# This tells Netlify to package these directories along with your function code.
# The paths are relative to your project's root directory.
[functions]
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200